name = "aiken-lang/flow-lending-smart-contract"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/flow-lending-smart-contract'"

[repository]
user = "aiken-lang"
project = "flow-lending-smart-contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
